### ISSUE TITLE
認証をせずにサインインしている

### ISSUE THREAD

**Issue by RuiOkazaki** [yumekiti/eccSchoolApp-api#5]
jwtに変換しているだけでは意味がないから認証して欲しい><

**Comment by yumekiti** [comment]
kwsk

**Comment by yumekiti** [comment]
学校サイトの認証に通さずjwtを返しているので認証の意味が無い、なので下記を実装する。

- 学校の認証に通す
- レスポンスがokならjwtを返す
- レスポンスがnoなら403を返す
- ~~実装するのを忘れてた事を隠蔽する~~

**Comment by yumekiti** [comment]
実装済み
https://github.com/yumekiti/eccSchoolApp-api/commit/e039cf4ea9dfa850c6eebf4268848f09b14c6562
