### ISSUE TITLE
講師アカウントでサインインできない

### ISSUE THREAD

**Issue by RuiOkazaki** [yumekiti/eccSchoolApp-api#6]
教員IDでログインする場合は3桁から5桁の数字になる
結局認証ベースで実装する方が良い

**Comment by yumekiti** [comment]
そもそも教師は学校のサイトにアクセスするのか…？
アクセスするとしても認証問題解決したら解決すると思われ

**Comment by yumekiti** [comment]
認証実装したので解決したとおもわれ
