### ISSUE TITLE
uuid routeをやめる？

### ISSUE THREAD

**Issue by RuiOkazaki** [yumekiti/eccSchoolApp-api#8]

**Comment by RuiOkazaki** [comment]
### 現状
`/signin`にアクセスするとuuidが格納されたjwtが返却される。
`/uuid`はjwtからuuidだけを引き抜いている
2度apiを叩くのはフロントからしても、バックエンドからしても嬉しくないはず。

### 改善策1
`/signin`にアクセスするとtokenとuuidをセットで返すようにする。

### 改善策2
`/uuid`ルートをなくし、apiのパスを`/{:uuid}/news`から`/news`に変更する
jwtにuuidが格納されているため、apiのパスで指定しなくても実装できるはず。

**Comment by yumekiti** [comment]
後者はキャッシュサーバーにキャッシュできなくなると思います

**Comment by yumekiti** [comment]
前者でとりあえず実装しました。
https://github.com/yumekiti/eccSchoolApp-api/commit/713ba43df773ce16060b38ff874003d716692069
